version: "3.9"
services:
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msvc_sum
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-sum:
    container_name: msvc-sum
    image: jonadare/tenpo-msvc-sum:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-sum/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: postgres14:5432
      DB_DATABASE: msvc_sum
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      PERCENTAGE_URL: http://msvc-percentage:8002
      REQUEST_PER_MINUTE: 3
      PERCENTAGE_API_MAX_ATTEMPTS: 3
      PERCENTAGE_API_POLLING_FREQUENCY: 1800000
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always

  msvc-percentage:
    container_name: msvc-percentage
    image: jonadare/tenpo-msvc-percentage:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-percentage/Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      PERCENTAGE_RANDOM_GENERATION_FREQUENCY: 1800000
    networks:
      - spring


volumes:
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring